<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Middleware\" />
    <Folder Include="Models\Dtos\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mapper.Domain\Mapper.Domain.csproj" />
    <ProjectReference Include="..\Mapper.Infrastructure\Mapper.Infrastructure.csproj" />
  </ItemGroup>

</Project>
