//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Communication.Entities {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResEntities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEntities() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapper.Communication.Entities.ResEntities", typeof(ResEntities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Dispositivo: {0}, \n Nome do Dispositivo: {1},\n Sistema Operacional: {2},\n MAC do Dispositivo: {3}, HARDWARE: \n\n {4} \n\n Rede: \n\n{5}.
        /// </summary>
        public static string ABOUT_COMPUTER {
            get {
                return ResourceManager.GetString("ABOUT_COMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processador.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}, {1} , {2}  Núcleos, {3} Threads. ({4}ª Geração).
        /// </summary>
        public static string CPU_ABOUT {
            get {
                return ResourceManager.GetString("CPU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HD Externo.
        /// </summary>
        public static string EXTERNAL_HD {
            get {
                return ResourceManager.GetString("EXTERNAL_HD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NVMe Externo.
        /// </summary>
        public static string EXTERNAL_NVME {
            get {
                return ResourceManager.GetString("EXTERNAL_NVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SSD Externo.
        /// </summary>
        public static string EXTERNAL_SSD {
            get {
                return ResourceManager.GetString("EXTERNAL_SSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa de Vídeo.
        /// </summary>
        public static string GPU {
            get {
                return ResourceManager.GetString("GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}, {1} {2}, GDDR {3}.
        /// </summary>
        public static string GPU_ABOUT {
            get {
                return ResourceManager.GetString("GPU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  IPV4: {0}, \n Sub Rede: {1},\n Gateway: {2}, DNS Primário: {3}, \n DNS Secundário: {4}, \n Domínio: {5};.
        /// </summary>
        public static string IP_ABOUT {
            get {
                return ResourceManager.GetString("IP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa Mãe.
        /// </summary>
        public static string MOTHERBOARD {
            get {
                return ResourceManager.GetString("MOTHERBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa mãe {0}, LGA {1}, Fabricante: {2}.
        /// </summary>
        public static string MOTHERBOARD_ABOUT {
            get {
                return ResourceManager.GetString("MOTHERBOARD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Memória RAM.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} GB DDR {2} {3}.
        /// </summary>
        public static string RAM_ABOUT {
            get {
                return ResourceManager.GetString("RAM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Armazenamento.
        /// </summary>
        public static string STORAGE {
            get {
                return ResourceManager.GetString("STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Armazenamento: {0}, Capacidade Total: {1} GB, Espaço Ocupado: {2} GB, Espaço Livre: {3} GB. .
        /// </summary>
        public static string STORAGE_ABOUT {
            get {
                return ResourceManager.GetString("STORAGE_ABOUT", resourceCulture);
            }
        }
    }
}
